# shell tools
brew "tmux"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "ripgrep"

# vim tools
brew "neovim"
brew "tree-sitter-cli"

# languages
brew "node"
brew "pyenv"
brew "pyenv-virtualenv"
brew "rustup"

# package managers
brew "yarn"
